---
name: Simo-Util
version: 0.01_01
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Utility Class for Simo
license: perl
resources:
  license: ~
build_requires:
  Test::More: 0
provides:
  Simo::Util:
    file: lib/Simo/Util.pm
    version: 0.01_01
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
